### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by moodah** [chlablak/pollson-server#1]
- [x] add questions to open room
- [x] add users who have answered to db
- [x] check that users have not yet answered
- [ ] clean room when it is closed
